name: Auto Scrape

# on:
#   push:
#     branches:
#       - master

on:
  push:
    branches:
      - main
  schedule:
    - cron: "15 10 * * *" # Every Day at 4PM NST (10:15am UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          # Install Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Install xvfb for virtual display
          sudo apt-get install -y xvfb
          
          # Install Python dependencies
          pip install -r requirements.txt

      - name: Execute Scraping Script
        run: |
          # Start virtual display
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99
          sleep 3
          
          # Run the scraper
          python scrape_floorsheet.py
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable

      - name: Commit and Push Files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"        
          git add .
          git commit -m "Data Scraped Successfully" -a || echo "No changes to commit"
          git push origin main

      # - name: Push changes
      #   uses: ad-m/github-push-action@main
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
